### ISSUE TITLE
How to get per instance costs?

### ISSUE THREAD

**Issue by cohenaj194** [ColbyAley/cloudability#8]
I'm not sure if this is the right place to raise this issue, but I am curious how to use this gem to gain more in depth reports. 

Can this gem be used to get the costs for individual instances?  Can it be used to pull `tag_explorer` reports found in https://app.cloudability.com/#/tag_explorer?  If so how? The readme could definitely use some more details.

**Comment by cp** [comment]
Hi @cohenaj194!

This gem does not support the tag explorer. From their [api documentation](http://developers.cloudability.com/) it appears the Cloudability API does not support tag explorer reports. If I'm wrong, or if you find anything else in the API docs you'd like the gem to support, I'd be happy to add the relevant capabilities.

The README is indeed fairly vague. Pull requests are always welcome 😄 

Cheers,
Colby
